#!/usr/bin/perl
use Getopt::Long;

use strict;

my $notify="/usr/local/bin/notifyEvent";
-x $notify or die "Can't run $notify";

my $mac=qx(cat /sys/class/net/eth0/address);
chomp $mac;

my $going = 1;
my $server="webpi2";
my $port=50051;
my $verbose =0;

sub catch_sig {
  my $signame = shift;
  $going= 0;
}

$SIG{INT} = \&catch_sig;  # best strategy

sub sendTemp()
{
  my $temp=qx(/opt/vc/bin/vcgencmd measure_temp);
  chomp $temp;
  $temp=~ s/temp=(.*\d+.\d).*/$1/;

  #print "$temp\n";
  my $cmd="$notify -v $temp -c $mac -p $port -s $server";
  print "$cmd\n";
  qx($cmd);
}


GetOptions ( "port=i" => \$port, # numeric
             "server=s" => \$server, # string
             "verbose" => \$verbose) # flag
or die("Error in command line arguments\n");

while($going)
{
    sendTemp();
    my $t=300;
    while($going and ($t > 0))
    {
     $t-=sleep $t;
    }
}

